import { useState } from 'react';
import API, { getApiErrorMessage } from '../../src/api';
import { downloadBlob } from '../../src/adminMaster';
import styles from './SyllabusReview.module.css';

export default function SyllabusDraftActions({courseId,review,subjectKey,disabled,canReset,onReset}) {
  const [busy,setBusy]=useState(false),[error,setError]=useState(''),[code,setCode]=useState(''),[reason,setReason]=useState(''),[cancel,setCancel]=useState(false);
  async function download(subject) {setBusy(true);setError('');try{const r=await API.get(`/courses/${courseId}/syllabus-review/reviews/${review.id}/syllabus.pdf`,{params:{subject_key:subject},responseType:'blob'});downloadBlob(r.data,`SYS_${subject?'Subject':'Complete'}_Syllabus_${courseId}_v${review.version}.pdf`);}catch(e){setError('Unable to download saved syllabus. Save content and check permissions first.');}finally{setBusy(false);}}
  async function reset() {if(!window.confirm('Clear this entire unapproved working syllabus and cancel confirmed review requests? A recovery snapshot will be retained.'))return;setBusy(true);setError('');try{const r=await API.post(`/courses/${courseId}/syllabus-review/reviews/${review.id}/reset`,{version:review.version,course_code:code,reason,cancel_requests:cancel});onReset(r.data);setCode('');setReason('');setCancel(false);}catch(e){setError(getApiErrorMessage(e));}finally{setBusy(false);}}
  return <section><div className={styles.actions}><button disabled={disabled||busy||!review.nodes.length} onClick={()=>download()}>Download complete syllabus PDF</button>{subjectKey&&<button disabled={disabled||busy} onClick={()=>download(subjectKey)}>Download subject syllabus PDF</button>}</div>{disabled&&<p>Save changes before downloading or clearing the syllabus.</p>}{error&&<div className={styles.error} role="alert">{error}</div>}{canReset&&<details className={styles.import}><summary>Advanced actions</summary><h3>Clear unapproved syllabus</h3><p>{['subject','unit','topic','subtopic'].map(l=>`${review.nodes.filter(n=>n.level===l).length} ${l}s`).join(' · ')}</p><p>Only an unapproved, unattached working syllabus can be cleared. Any final subject approval or existing academic records blocks this action. A recovery snapshot and audit record will be retained.</p><label>Type the exact course code<input value={code} onChange={e=>setCode(e.target.value)}/></label><label>Reason<textarea maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)}/></label><label className={styles.resetCheck}><input type="checkbox" checked={cancel} onChange={e=>setCancel(e.target.checked)}/>Cancel active review requests and notify reviewers</label><button disabled={disabled||busy||!code||reason.trim().length<5||!review.nodes.length} onClick={reset}>Clear unapproved syllabus</button><p>Download a fresh Excel template after clearing. Older workbooks will no longer be valid.</p></details>}</section>;
}
