"""Ownership-scoped, SYS-branded institutional course and subject PDF reports."""

from __future__ import annotations

from datetime import datetime
from io import BytesIO
from typing import Any
from xml.sax.saxutils import escape

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import PageBreak, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from app.services.master_profile_pdf import (
    IST,
    SYS_BLUE,
    SYS_BORDER,
    SYS_MUTED,
    SYS_PALE,
    SYS_PURPLE,
    _display,
    _header_footer,
    _paragraph,
    _section,
    _styles,
)


def _percentage(value: Any) -> str:
    if value is None:
        return "Not configured"
    numeric = float(value)
    return f"{numeric:g}%"


def _counts(subjects: list[dict]) -> dict[str, int]:
    units = [unit for subject in subjects for unit in subject.get("units", [])]
    topics = [topic for unit in units for topic in unit.get("topics", [])]
    subtopics = [subtopic for topic in topics for subtopic in topic.get("subtopics", [])]
    return {"subjects": len(subjects), "units": len(units), "topics": len(topics), "subtopics": len(subtopics)}


def _report_title(payload: dict, report_type: str) -> str:
    subject = payload.get("subject")
    if report_type == "syllabus":
        return "Subject Syllabus" if subject else "Course Syllabus"
    return "Subject Profile" if subject else "Course Profile"


def _identity(story: list, payload: dict, styles: dict, generated_at: datetime, generated_by: str) -> None:
    course = payload.get("course") or {}
    subject = payload.get("subject")
    title = f"{course.get('title', 'SYS course')} - {subject['name']}" if subject else course.get("title", "SYS course")
    story.extend([
        _paragraph(title, styles["name"]),
        _paragraph(f"Course code: {_display(course.get('programme_code'), 'Not configured')}  |  {'Subject academic profile' if subject else 'Complete institutional course profile'}", styles["subtitle"]),
        Spacer(1, 8),
        _paragraph(f"Generated: {generated_at.strftime('%d %b %Y, %I:%M:%S %p')} IST   |   Generated by: {generated_by}", styles["notice"]),
        Spacer(1, 15),
    ])


def _ownership_pairs(payload: dict) -> list[tuple[str, Any]]:
    coordinators = payload.get("coordinators") or []
    experts = payload.get("experts") or []
    pairs = [("Course coordinators", len(coordinators)), ("Subject experts", len(experts))]
    for index, person in enumerate(coordinators, start=1):
        detail = " | ".join(filter(None, [person.get("employee_code"), person.get("department"), person.get("designation")]))
        pairs.append((f"Coordinator {index}", f"{person.get('name', 'Not available')}{f' ({detail})' if detail else ''}"))
    for index, person in enumerate(experts, start=1):
        detail = " | ".join(filter(None, [person.get("subject_name"), person.get("employee_code"), person.get("department")]))
        pairs.append((f"Subject expert {index}", f"{person.get('name', 'Not available')}{f' ({detail})' if detail else ''}"))
    if not coordinators:
        pairs.append(("Coordinator status", "No course coordinator assigned yet"))
    if not experts:
        pairs.append(("Subject-expert status", "No subject experts assigned yet"))
    return pairs


def _hierarchy_story(subjects: list[dict], styles: dict, width: float) -> list:
    if not subjects:
        return [_paragraph("No syllabus subjects have been configured yet.", styles["empty"]), Spacer(1, 13)]
    result = []
    subject_style = ParagraphStyle("SYSCourseReportSubject", parent=styles["section"], textColor=SYS_BLUE, spaceBefore=11, spaceAfter=6)
    unit_style = ParagraphStyle("SYSCourseReportUnit", parent=styles["value"], leftIndent=11, spaceBefore=6, spaceAfter=3)
    topic_style = ParagraphStyle("SYSCourseReportTopic", parent=styles["notice"], leftIndent=24, textColor=SYS_BLUE, spaceBefore=3, spaceAfter=2)
    subtopic_style = ParagraphStyle("SYSCourseReportSubtopic", parent=styles["notice"], leftIndent=39, fontSize=7.6, leading=11, spaceAfter=2)
    for subject in subjects:
        result.append(Paragraph(escape(f"{subject['name']} | Subject weightage: {_percentage(subject.get('weight_percent'))}"), subject_style))
        if not subject.get("units"):
            result.append(_paragraph("No units configured yet.", styles["empty"]))
        for unit in subject.get("units", []):
            label = f"Unit {unit.get('sequence', '')}: {unit['name']} | {_percentage(unit.get('weight_percent'))}"
            result.append(Paragraph(escape(label), unit_style))
            if not unit.get("topics"):
                result.append(Paragraph("No topics configured yet.", topic_style))
            for topic in unit.get("topics", []):
                result.append(Paragraph(escape(f"Topic: {topic['name']} | {_percentage(topic.get('weight_percent'))}"), topic_style))
                if not topic.get("subtopics"):
                    result.append(Paragraph("No subtopics configured yet.", subtopic_style))
                for subtopic in topic.get("subtopics", []):
                    result.append(Paragraph(escape(f"- {subtopic['name']} | {_percentage(subtopic.get('weight_percent'))}"), subtopic_style))
        result.append(Spacer(1, 7))
    return result


def _subject_summary(subjects: list[dict], styles: dict, width: float) -> list:
    rows = [["Subject", "Weightage", "Units", "Topics", "Subtopics"]]
    for subject in subjects:
        counts = _counts([subject])
        rows.append([subject.get("name", "Not available"), _percentage(subject.get("weight_percent")), str(counts["units"]), str(counts["topics"]), str(counts["subtopics"])])
    if len(rows) == 1:
        return [_paragraph("No syllabus subjects configured yet.", styles["empty"]), Spacer(1, 12)]
    table_rows = [[_paragraph(cell, styles["value"] if index == 0 else styles["notice"]) for cell in row] for index, row in enumerate(rows)]
    table = Table(table_rows, colWidths=[width * .36, width * .19, width * .15, width * .15, width * .15], repeatRows=1, hAlign="LEFT")
    table.setStyle(TableStyle([("BACKGROUND", (0, 0), (-1, 0), SYS_PALE), ("BOX", (0, 0), (-1, -1), .6, SYS_BORDER), ("INNERGRID", (0, 0), (-1, -1), .35, SYS_BORDER), ("VALIGN", (0, 0), (-1, -1), "TOP"), ("LEFTPADDING", (0, 0), (-1, -1), 7), ("RIGHTPADDING", (0, 0), (-1, -1), 5), ("TOPPADDING", (0, 0), (-1, -1), 7), ("BOTTOMPADDING", (0, 0), (-1, -1), 7), ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#FAFBFE")])]))
    return [Paragraph("Subject-wise syllabus and weightages", styles["section"]), table, Spacer(1, 14)]


def build_course_profile_pdf(payload: dict, *, generated_by: str, report_type: str = "profile", generated_at: datetime | None = None) -> bytes:
    """Generate a course-wide or subject-scoped report from pre-authorized aggregate data."""
    if report_type not in {"profile", "syllabus"}:
        raise ValueError("Unsupported course report type")
    issued_at = (generated_at or datetime.now(IST)).astimezone(IST)
    title = _report_title(payload, report_type)
    output = BytesIO()
    document = SimpleDocTemplate(output, pagesize=A4, leftMargin=18 * mm, rightMargin=18 * mm, topMargin=95, bottomMargin=68, pageCompression=0, title=f"SYS {title}", author="SYS - Strengthen Your Skills")
    styles = _styles()
    styles['section'].keepWithNext = True
    width = A4[0] - 36 * mm
    course = payload.get("course") or {}
    subject = payload.get("subject")
    subjects = payload.get("subjects") or []
    counts = _counts(subjects)
    activity = payload.get("activity") or {}
    story = []
    _identity(story, payload, styles, issued_at, generated_by)

    identity = [("Course title", course.get("title")), ("Course code", _display(course.get("programme_code"), "Not configured")), ("Course category", str(course.get("programme_category") or "Not configured").replace("_", " ").title()), ("Publication status", "Active" if course.get("is_active") else "Draft"), ("Examination", _display(course.get("examination_name"), "Not applicable")), ("Examination authority", _display(course.get("examination_authority"), "Not configured")), ("Learning objective", _display(course.get("target_purpose"), "Learning objective not configured")), ("Course description", _display(course.get("description"), "Course description not configured"))]
    if subject:
        identity.extend([("Assigned subject", subject.get("name")), ("Subject course weightage", _percentage(subject.get("weight_percent")))])
    if payload.get('syllabus_status'):
        identity.append(('Syllabus configuration status', payload['syllabus_status']))
    story.extend(_section("Course identity and examination", identity, styles, width))
    story.extend(_section("Academic ownership", _ownership_pairs(payload), styles, width))

    if report_type == "syllabus":
        story.extend(_section("Syllabus coverage", [("Subjects", counts["subjects"]), ("Units", counts["units"]), ("Topics", counts["topics"]), ("Subtopics", counts["subtopics"])], styles, width))
        story.extend(_hierarchy_story(subjects, styles, width))
    else:
        story.extend(_section("Syllabus overview", [("Subjects configured", counts["subjects"]), ("Units configured", counts["units"]), ("Topics configured", counts["topics"]), ("Subtopics configured", counts["subtopics"])], styles, width))
        story.extend(_subject_summary(subjects, styles, width))
        configured = payload.get("configured") or {}
        story.extend(_section("Academic weightage and prioritization", [("Subject weightages", configured.get("subjects", 0)), ("Unit weightages", configured.get("units", 0)), ("Topic weightages", configured.get("topics", 0)), ("Subtopic weightages", configured.get("subtopics", 0)), ("Weightage readiness", payload.get("weightage_readiness", "Not configured yet"))], styles, width))
        enrolled = activity.get("students", 0)
        story.extend(_section("Student participation", [("Students enrolled", enrolled), ("Enrollment status", "Student enrollment is active" if enrolled else "No students enrolled yet")], styles, width))
        sessions = activity.get("learning_sessions", 0)
        story.extend(_section("Learning activity", [("Learning sessions", sessions), ("Learning status", "Learning activity recorded" if sessions else "Learning has not started yet"), ("Completed sessions", activity.get("completed_learning_sessions", 0))], styles, width))
        assessments = activity.get("assessments", 0)
        story.extend(_section("Assessment and performance summary", [("Assessments created", assessments), ("Assessment status", "Assessments available" if assessments else "No assessments created yet"), ("Published assessments", activity.get("published_assessments", 0)), ("Student assessment attempts", activity.get("assessment_attempts", 0)), ("Average performance", f"{activity['average_percentage']:.1f}%" if activity.get("average_percentage") is not None else "Not assessed yet")], styles, width))
        questions = activity.get("questions", 0)
        story.extend(_section("Question bank and academic intelligence", [("Available questions", questions), ("Content status", "Question bank available" if questions else "No questions created yet")], styles, width))
        groups = activity.get("remedial_groups", 0)
        story.extend(_section("Remedial learning and academic support", [("Remedial groups", groups), ("Support status", "Remedial support active" if groups else "No remedial learning required yet")], styles, width))
        readiness = [("Course identity", "Configured" if course.get("title") and course.get("programme_code") else "Needs attention"), ("Academic syllabus", "Configured" if subjects else "Needs attention"), ("Course coordinator", "Assigned" if payload.get("coordinators") else "Not assigned"), ("Subject experts", "Assigned" if payload.get("experts") else "Not assigned"), ("Academic weightages", payload.get("weightage_readiness", "Not configured yet")), ("Student enrollment", "Started" if enrolled else "Not started yet")]
        story.extend(_section("Course readiness" if not subject else "Subject readiness", readiness, styles, width))

    callback = lambda canvas, doc: _header_footer(canvas, doc, title=title, generated_at=issued_at, generated_by=generated_by)
    document.build(story, onFirstPage=callback, onLaterPages=callback)
    return output.getvalue()


def build_coordinator_courses_pdf(payloads: list[dict], *, generated_by: str, generated_at: datetime | None = None) -> bytes:
    """Generate one SYS-branded portfolio for every course coordinated by a faculty member."""
    issued_at = (generated_at or datetime.now(IST)).astimezone(IST)
    title = "Course Coordinator Portfolio"
    output = BytesIO()
    document = SimpleDocTemplate(output, pagesize=A4, leftMargin=18 * mm, rightMargin=18 * mm, topMargin=95, bottomMargin=68, pageCompression=0, title=f"SYS {title}", author="SYS - Strengthen Your Skills")
    styles = _styles()
    styles["section"].keepWithNext = True
    width = A4[0] - 36 * mm
    story = [
        _paragraph("Assigned Course Portfolio", styles["name"]),
        _paragraph(f"Course coordinator: {generated_by}  |  {len(payloads)} assigned course{'s' if len(payloads) != 1 else ''}", styles["subtitle"]),
        Spacer(1, 8),
        _paragraph(f"Generated: {issued_at.strftime('%d %b %Y, %I:%M:%S %p')} IST", styles["notice"]),
        Spacer(1, 15),
    ]
    if not payloads:
        story.append(_paragraph("No course-coordinator responsibility is assigned to this faculty account.", styles["empty"]))
    for index, payload in enumerate(payloads, start=1):
        if index > 1:
            story.append(PageBreak())
        course = payload.get("course") or {}
        subjects = payload.get("subjects") or []
        counts = _counts(subjects)
        activity = payload.get("activity") or {}
        story.extend([
            _paragraph(f"{index}. {course.get('title', 'SYS course')}", styles["name"]),
            _paragraph(f"Course code: {_display(course.get('programme_code'), 'Not configured')}", styles["subtitle"]),
            Spacer(1, 12),
        ])
        story.extend(_section("Course identity and purpose", [
            ("Course category", str(course.get("programme_category") or "Not configured").replace("_", " ").title()),
            ("Publication status", "Active" if course.get("is_active") else "Draft"),
            ("Examination", _display(course.get("examination_name"), "Not applicable")),
            ("Examination authority", _display(course.get("examination_authority"), "Not configured")),
            ("Learning objective", _display(course.get("target_purpose"), "Not configured")),
            ("Description", _display(course.get("description"), "Not configured")),
        ], styles, width))
        story.extend(_section("Academic structure and ownership", [
            ("Subjects", counts["subjects"]), ("Units", counts["units"]),
            ("Topics", counts["topics"]), ("Subtopics", counts["subtopics"]),
            ("Subject names", ", ".join(row.get("name", "Unnamed subject") for row in subjects) or "No subjects configured"),
            ("Subject experts", len(payload.get("experts") or [])),
            ("Syllabus status", payload.get("syllabus_status") or "Published academic structure"),
            ("Weightage readiness", payload.get("weightage_readiness") or "Not configured"),
        ], styles, width))
        story.extend(_section("Learning and assessment activity", [
            ("Enrolled students", activity.get("students", 0)),
            ("Learning sessions", activity.get("learning_sessions", 0)),
            ("Completed sessions", activity.get("completed_learning_sessions", 0)),
            ("Assessments", activity.get("assessments", 0)),
            ("Published assessments", activity.get("published_assessments", 0)),
            ("Assessment attempts", activity.get("assessment_attempts", 0)),
            ("Question bank", activity.get("questions", 0)),
            ("Remedial groups", activity.get("remedial_groups", 0)),
        ], styles, width))
    callback = lambda canvas, doc: _header_footer(canvas, doc, title=title, generated_at=issued_at, generated_by=generated_by)
    document.build(story, onFirstPage=callback, onLaterPages=callback)
    return output.getvalue()


def build_subject_expert_assignments_pdf(payloads: list[dict], *, generated_by: str, generated_at: datetime | None = None) -> bytes:
    """Generate a concise SYS-branded register of subjects assigned across courses."""
    issued_at = (generated_at or datetime.now(IST)).astimezone(IST)
    title = "Subject Expert Assignment Portfolio"
    output = BytesIO()
    document = SimpleDocTemplate(output, pagesize=A4, leftMargin=18 * mm, rightMargin=18 * mm, topMargin=95, bottomMargin=68, pageCompression=0, title=f"SYS {title}", author="SYS - Strengthen Your Skills")
    styles = _styles()
    styles["section"].keepWithNext = True
    width = A4[0] - 36 * mm
    course_count = len({payload.get("course", {}).get("id") for payload in payloads})
    story = [
        _paragraph("Assigned Subject Portfolio", styles["name"]),
        _paragraph(f"Subject expert: {generated_by}  |  {len(payloads)} assigned subject{'s' if len(payloads) != 1 else ''} across {course_count} course{'s' if course_count != 1 else ''}", styles["subtitle"]),
        Spacer(1, 8),
        _paragraph(f"Generated: {issued_at.strftime('%d %b %Y, %I:%M:%S %p')} IST", styles["notice"]),
        Spacer(1, 15),
    ]
    if not payloads:
        story.append(_paragraph("No subject-expert responsibility is assigned to this faculty account.", styles["empty"]))
    if payloads:
        rows = [["Course", "Course code", "Assigned subject", "Review status"]]
        for payload in payloads:
            course = payload.get("course") or {}
            subject = payload.get("subject") or {}
            assignment = payload.get("assignment") or {}
            rows.append([
                course.get("title", "SYS course"),
                _display(course.get("programme_code"), "Not configured"),
                subject.get("name", "Assigned subject"),
                str(assignment.get("review_status") or "ASSIGNED").replace("_", " ").title(),
            ])
        table_rows = [[_paragraph(cell, styles["value"] if row_index else styles["notice"]) for cell in row] for row_index, row in enumerate(rows)]
        table = Table(table_rows, colWidths=[width * .34, width * .18, width * .28, width * .20], repeatRows=1, hAlign="LEFT")
        table.setStyle(TableStyle([("BACKGROUND", (0, 0), (-1, 0), SYS_PALE), ("BOX", (0, 0), (-1, -1), .6, SYS_BORDER), ("INNERGRID", (0, 0), (-1, -1), .35, SYS_BORDER), ("VALIGN", (0, 0), (-1, -1), "TOP"), ("LEFTPADDING", (0, 0), (-1, -1), 7), ("RIGHTPADDING", (0, 0), (-1, -1), 5), ("TOPPADDING", (0, 0), (-1, -1), 7), ("BOTTOMPADDING", (0, 0), (-1, -1), 7), ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#FAFBFE")])]))
        story.extend([Paragraph("Assigned subjects across SYS courses", styles["section"]), table])
    callback = lambda canvas, doc: _header_footer(canvas, doc, title=title, generated_at=issued_at, generated_by=generated_by)
    document.build(story, onFirstPage=callback, onLaterPages=callback)
    return output.getvalue()
