"""
SYS Assessment / Notification constants (P0-009)
"""

# Assessment categories (purpose/scope)
ASSESSMENT_CATEGORIES = (
    "TOPIC_MASTERY",
    "PERIODIC_EVALUATION",
    "CUMULATIVE_EVALUATION",
    "FINAL_READINESS",
)

# Assessment types
ASSESSMENT_TYPES = (
    "TOPIC_TEST",
    "WEEKLY_TEST",
    "MONTHLY_TEST",
    "GRAND_TEST",
    "FINAL_GRAND_TEST",
)

TYPE_TO_CATEGORY = {
    "TOPIC_TEST": "TOPIC_MASTERY",
    "WEEKLY_TEST": "PERIODIC_EVALUATION",
    "MONTHLY_TEST": "PERIODIC_EVALUATION",
    "GRAND_TEST": "CUMULATIVE_EVALUATION",
    "FINAL_GRAND_TEST": "FINAL_READINESS",
}

MULTI_SUBJECT_TYPES = {
    "WEEKLY_TEST",
    "MONTHLY_TEST",
    "GRAND_TEST",
    "FINAL_GRAND_TEST",
}

ASSESSMENT_STATUSES = ("DRAFT", "PUBLISHED", "ARCHIVED")

DIFFICULTIES = ("EASY", "MEDIUM", "HARD", "ADVANCED")

QUESTION_STATUSES = ("DRAFT", "REVIEW", "APPROVED", "ACTIVE", "ARCHIVED", "INACTIVE")

QUESTION_TYPES = (
    "SINGLE_MCQ",
    "MULTI_MCQ",
    "TRUE_FALSE",
    "FILL_BLANK",
    "MCQ",  # legacy alias → treat as SINGLE_MCQ
)

SIMILARITY_CLASSES = (
    "EXACT_PREVIOUS",
    "SIMILAR",
    "CONCEPT_VARIANT",
    "NOVEL",
)

REUSE_POLICIES = ("EXACT_PREVIOUS", "CONCEPT_VARIANT", "NOVEL", "MIXED")

PRIORITY_LABELS = ("VERY_HIGH", "HIGH", "MEDIUM", "LOW")

TREND_LABELS = ("INCREASING", "STABLE", "DECREASING", "UNKNOWN")

ATTEMPT_STATUSES = (
    "NOT_STARTED",
    "IN_PROGRESS",
    "SUBMITTED",
    "AUTO_SUBMITTED",
    "EVALUATED",
    "CANCELLED",
)

NOTIFICATION_EVENTS = (
    "ASSESSMENT_PUBLISHED",
    "ASSESSMENT_COMPLETED",
    "RESULTS_PUBLISHED",
    "REPORT_GENERATED",
    "REPORT_CARD_GENERATED",
    "ASSESSMENT_EVALUATED",
    "ANSWER_KEY_AVAILABLE",
    # P0-012
    "RESULT_AVAILABLE",
    "PERFORMANCE_ANALYSIS_AVAILABLE",
    "WEEKLY_PERFORMANCE_REPORT",
    "MONTHLY_PERFORMANCE_REPORT",
    "GRAND_ASSESSMENT_ANALYSIS",
    "FINAL_GRAND_ASSESSMENT_ANALYSIS",
    "SIGNIFICANT_PERFORMANCE_DECLINE",
    "CRITICAL_LEARNING_GAP",
    "REPEATED_WEAKNESS",
    "SIGNIFICANT_IMPROVEMENT",
    "EXAM_READINESS_UPDATED",
    "ASSESSMENT_REMINDER",
    "LEARNING_RECOMMENDATION",
    "REMEDIAL_PLAN_AVAILABLE",
    "ACADEMIC_ANNOUNCEMENT",
    "SYSTEM_ALERT",
)

NOTIFICATION_STATUSES = (
    "PENDING",
    "PROCESSING",
    "SENT",
    "FAILED",
    "RETRYING",
    "PARTIAL",
    "DELIVERED",
    "READ",
)

NOTIFICATION_CHANNELS = ("EMAIL", "IN_APP", "SMS")

NOTIFICATION_SEVERITIES = ("INFO", "SUCCESS", "WARNING", "CRITICAL")

GAP_CLASSIFICATIONS = (
    "MASTERED",
    "STRONG",
    "ADEQUATE",
    "DEVELOPING",
    "WEAK",
    "CRITICAL_GAP",
)

ANALYZER_TRENDS = (
    "IMPROVING",
    "DECLINING",
    "STABLE",
    "FLUCTUATING",
    "RECOVERING",
    "STAGNATING",
)

RECIPIENT_TYPES = (
    "SYSTEM_ADMIN",
    "COURSE_COORDINATOR",
    "HIGHER_OFFICIAL",
    "CUSTOM_RECIPIENT",
    "STUDENT",
    "SUBJECT_EXPERT",
)

NOTIFICATION_FREQUENCIES = (
    "IMMEDIATE",
    "DAILY_SUMMARY",
    "WEEKLY_SUMMARY",
    "MONTHLY_SUMMARY",
)

NOTIFICATION_PREF_CATEGORIES = (
    "ASSESSMENT_RESULTS",
    "PERFORMANCE_REPORTS",
    "IMPORTANT_ALERTS",
    "ROUTINE",
)

MAX_NOTIFICATION_RETRIES = 3

# =========================
# Learning Sessions (P0-013)
# =========================
LEARNING_SESSION_MODES = ("COMMON", "INDIVIDUAL", "HYBRID")

LEARNING_SESSION_STATUSES = (
    "DRAFT",
    "SCHEDULED",
    "READY",
    "IN_PROGRESS",
    "PAUSED",
    "COMPLETED",
    "CANCELLED",
    "ARCHIVED",
)

# Allowed lifecycle transitions (from -> to)
LEARNING_SESSION_TRANSITIONS = {
    "DRAFT": {"SCHEDULED", "READY", "CANCELLED"},
    "SCHEDULED": {"READY", "IN_PROGRESS", "CANCELLED"},
    "READY": {"IN_PROGRESS", "CANCELLED"},
    "IN_PROGRESS": {"PAUSED", "COMPLETED", "CANCELLED"},
    "PAUSED": {"IN_PROGRESS", "COMPLETED", "CANCELLED"},
    "COMPLETED": {"ARCHIVED"},
    "CANCELLED": {"ARCHIVED"},
    "ARCHIVED": set(),
}

LEARNING_PARTICIPANT_ROLES = ("STUDENT", "FACILITATOR", "TEACHER", "AI_LECTURER")

LEARNING_PARTICIPANT_STATUSES = (
    "INVITED",
    "JOINED",
    "ACTIVE",
    "LEFT",
    "REMOVED",
    "COMPLETED",  # participant-level completion (distinct from session status)
)

LEARNING_ACTIVITY_TYPES = (
    "INTRODUCTION",
    "LECTURE",
    "EXPLANATION",
    "EXAMPLE",
    "QUESTION",
    "DISCUSSION",
    "PRACTICE",
    "ASSESSMENT",
    "REFLECTION",
    "SUMMARY",
)

LEARNING_ACTIVITY_SCOPES = ("COMMON", "PARTICIPANT_SPECIFIC")

LEARNING_ACTIVITY_STATUSES = ("PENDING", "READY", "IN_PROGRESS", "COMPLETED", "SKIPPED")

LEARNING_OBJECTIVE_STATUSES = ("PENDING", "IN_PROGRESS", "COMPLETED")

LEARNING_EVIDENCE_EVENT_TYPES = (
    "SESSION_STARTED",
    "SESSION_COMPLETED",
    "SESSION_PAUSED",
    "ACTIVITY_STARTED",
    "ACTIVITY_COMPLETED",
    "QUESTION_ASKED",
    "ANSWER_SUBMITTED",
    "EXPLANATION_VIEWED",
    "PRACTICE_COMPLETED",
    "PARTICIPATION_RECORDED",
    "OBJECTIVE_COMPLETED",
    "AI_INTERACTION",
)
