"""
SYS Assessment / Notification constants (P0-009)
"""

# Assessment categories (purpose/scope)
ASSESSMENT_CATEGORIES = (
    "TOPIC_MASTERY",
    "PERIODIC_EVALUATION",
    "CUMULATIVE_EVALUATION",
    "FINAL_READINESS",
)

# Assessment types
ASSESSMENT_TYPES = (
    "TOPIC_TEST",
    "WEEKLY_TEST",
    "MONTHLY_TEST",
    "GRAND_TEST",
    "FINAL_GRAND_TEST",
)

TYPE_TO_CATEGORY = {
    "TOPIC_TEST": "TOPIC_MASTERY",
    "WEEKLY_TEST": "PERIODIC_EVALUATION",
    "MONTHLY_TEST": "PERIODIC_EVALUATION",
    "GRAND_TEST": "CUMULATIVE_EVALUATION",
    "FINAL_GRAND_TEST": "FINAL_READINESS",
}

MULTI_SUBJECT_TYPES = {
    "WEEKLY_TEST",
    "MONTHLY_TEST",
    "GRAND_TEST",
    "FINAL_GRAND_TEST",
}

ASSESSMENT_STATUSES = ("DRAFT", "PUBLISHED", "ARCHIVED")

DIFFICULTIES = ("EASY", "MEDIUM", "HARD", "ADVANCED")

QUESTION_STATUSES = ("DRAFT", "REVIEW", "APPROVED", "ACTIVE", "ARCHIVED", "INACTIVE")

QUESTION_TYPES = (
    "SINGLE_MCQ",
    "MULTI_MCQ",
    "TRUE_FALSE",
    "FILL_BLANK",
    "MCQ",  # legacy alias → treat as SINGLE_MCQ
)

SIMILARITY_CLASSES = (
    "EXACT_PREVIOUS",
    "SIMILAR",
    "CONCEPT_VARIANT",
    "NOVEL",
)

REUSE_POLICIES = ("EXACT_PREVIOUS", "CONCEPT_VARIANT", "NOVEL", "MIXED")

PRIORITY_LABELS = ("VERY_HIGH", "HIGH", "MEDIUM", "LOW")

TREND_LABELS = ("INCREASING", "STABLE", "DECREASING", "UNKNOWN")

NOTIFICATION_EVENTS = (
    "ASSESSMENT_PUBLISHED",
    "ASSESSMENT_COMPLETED",
    "RESULTS_PUBLISHED",
    "REPORT_GENERATED",
    "REPORT_CARD_GENERATED",
)

NOTIFICATION_STATUSES = ("PENDING", "PROCESSING", "SENT", "FAILED", "RETRYING")

RECIPIENT_TYPES = (
    "SYSTEM_ADMIN",
    "COURSE_COORDINATOR",
    "HIGHER_OFFICIAL",
    "CUSTOM_RECIPIENT",
)

NOTIFICATION_FREQUENCIES = (
    "IMMEDIATE",
    "DAILY_SUMMARY",
    "WEEKLY_SUMMARY",
    "MONTHLY_SUMMARY",
)
