"""
SYS Assessment / Notification constants (P0-009)
"""

# Assessment categories (purpose/scope)
ASSESSMENT_CATEGORIES = (
    "TOPIC_MASTERY",
    "PERIODIC_EVALUATION",
    "CUMULATIVE_EVALUATION",
    "FINAL_READINESS",
)

# Assessment types
ASSESSMENT_TYPES = (
    "TOPIC_TEST",
    "WEEKLY_TEST",
    "MONTHLY_TEST",
    "GRAND_TEST",
    "FINAL_GRAND_TEST",
)

TYPE_TO_CATEGORY = {
    "TOPIC_TEST": "TOPIC_MASTERY",
    "WEEKLY_TEST": "PERIODIC_EVALUATION",
    "MONTHLY_TEST": "PERIODIC_EVALUATION",
    "GRAND_TEST": "CUMULATIVE_EVALUATION",
    "FINAL_GRAND_TEST": "FINAL_READINESS",
}

MULTI_SUBJECT_TYPES = {
    "WEEKLY_TEST",
    "MONTHLY_TEST",
    "GRAND_TEST",
    "FINAL_GRAND_TEST",
}

ASSESSMENT_STATUSES = ("DRAFT", "PUBLISHED", "ARCHIVED")

DIFFICULTIES = ("EASY", "MEDIUM", "HARD", "ADVANCED")

QUESTION_STATUSES = ("ACTIVE", "INACTIVE", "DRAFT")

NOTIFICATION_EVENTS = (
    "ASSESSMENT_PUBLISHED",
    "ASSESSMENT_COMPLETED",
    "RESULTS_PUBLISHED",
    "REPORT_GENERATED",
    "REPORT_CARD_GENERATED",
)

NOTIFICATION_STATUSES = ("PENDING", "PROCESSING", "SENT", "FAILED", "RETRYING")

RECIPIENT_TYPES = (
    "SYSTEM_ADMIN",
    "COURSE_COORDINATOR",
    "HIGHER_OFFICIAL",
    "CUSTOM_RECIPIENT",
)

NOTIFICATION_FREQUENCIES = (
    "IMMEDIATE",
    "DAILY_SUMMARY",
    "WEEKLY_SUMMARY",
    "MONTHLY_SUMMARY",
)
