import { useCallback, useEffect, useState } from "react";
import { adminListFaculty, assignAcademicReviewer, decideKnowledgePackage, getApiErrorMessage, getKnowledgeReviewWorkspace, getMyKnowledgeReviews, getPilotKnowledgeApprovalPreview, pilotApproveKnowledgePackages } from "../../src/api";
import styles from "./KnowledgeReviewWorkspace.module.css";

const label = (value) => String(value || "DRAFT").replaceAll("_", " ");
const pretty = (value) => JSON.stringify(value ?? [], null, 2);

function PackageCard({ item, admin, faculty, onRefresh }) {
  const [open, setOpen] = useState(false); const [comment, setComment] = useState("");
  const [facultyId, setFacultyId] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function assign() { setBusy(true); setError(""); try { await assignAcademicReviewer({ topic_id: item.topic_id, faculty_id: Number(facultyId) }); await onRefresh(); } catch (e) { setError(getApiErrorMessage(e, "Unable to assign reviewer.")); } finally { setBusy(false); } }
  async function decide(action) { if (comment.trim().length < 5) return setError("Enter a review comment of at least five characters."); setBusy(true); setError(""); try { await decideKnowledgePackage(item.package_id, { action, comment: comment.trim() }); setComment(""); await onRefresh(); } catch (e) { setError(getApiErrorMessage(e, "Unable to record the package decision.")); } finally { setBusy(false); } }
  const sections = item.revision ? [["Learning objectives",item.revision.objectives],["Prerequisites",item.revision.prerequisites],["Concepts",item.revision.concepts],["Definitions",item.revision.definitions],["Formulas and rules",item.revision.formulas],["Verified facts",item.revision.verified_facts],["Worked examples",item.revision.worked_examples],["Misconceptions",item.revision.misconceptions],["Examination relevance",item.revision.exam_relevance],["Subtopic coverage",item.revision.subtopic_coverage]] : [];
  return <article className={styles.card}><header className={styles.header}><div><h2>{item.subject_name}</h2><strong>{item.topic_name}</strong><p className={styles.meta}>Revision {item.current_revision} · {item.revision?.subtopic_coverage?.length || 0} mapped subtopics · Reviewers: {item.reviewers.map((r) => r.faculty_name).join(", ") || "Not assigned"}</p></div><span className={styles.badge}>{label(item.status)}</span></header><button className={styles.secondary} onClick={() => setOpen(!open)}>{open ? "Hide evidence" : "Inspect complete package"}</button>{open && <div className={styles.sections}>{sections.map(([name,value]) => <section className={styles.section} key={name}><h3>{name}</h3><pre>{pretty(value)}</pre></section>)}</div>}{error && <div className={styles.error}>{error}</div>}<div className={styles.actions}>{admin && <><select aria-label={`Reviewer for ${item.topic_name}`} value={facultyId} onChange={(e) => setFacultyId(e.target.value)}><option value="">Select faculty reviewer</option>{faculty.map((person) => <option key={person.id} value={person.id}>{person.name} · {person.employee_code || person.email}</option>)}</select><button className={styles.secondary} disabled={!facultyId || busy} onClick={assign}>Assign reviewer</button></>}<textarea placeholder="Record verification evidence, correction instructions, or approval rationale." value={comment} onChange={(e) => setComment(e.target.value)} />{admin && ["DRAFT","PILOT_APPROVED"].includes(item.status) && <button className={styles.primary} disabled={busy} onClick={() => decide("SUBMIT")}>Submit for expert review</button>}{!admin && item.status === "SOURCE_REVIEW" && <><button className={styles.primary} disabled={busy} onClick={() => decide("EXPERT_VERIFY")}>Expert verify</button><button className={styles.secondary} disabled={busy} onClick={() => decide("REQUEST_CHANGES")}>Request corrections</button></>}{admin && item.status === "EXPERT_VERIFIED" && <><button className={styles.primary} disabled={busy} onClick={() => decide("APPROVE")}>Approve package</button><button className={styles.secondary} disabled={busy} onClick={() => decide("REQUEST_CHANGES")}>Return for corrections</button></>}</div></article>;
}

export default function KnowledgeReviewWorkspace({ courseId, admin = false }) {
  const [data, setData] = useState(null); const [faculty, setFaculty] = useState([]); const [error, setError] = useState("");
  const [success, setSuccess] = useState(""); const [pilotPreview, setPilotPreview] = useState(null); const [pilotBusy, setPilotBusy] = useState(false);
  const load = useCallback(async () => { if (admin) { const [workspace, people] = await Promise.all([getKnowledgeReviewWorkspace(courseId), adminListFaculty()]); setData({ courses: [workspace.data], assignment_count: workspace.data.items.length }); setFaculty((people.data || []).filter((p) => p.is_active)); } else { const { data: payload } = await getMyKnowledgeReviews(); setData(payload); } }, [admin, courseId]);
  useEffect(() => { load().catch((e) => setError(getApiErrorMessage(e, "Unable to load knowledge-package reviews."))); }, [load]);
  async function preparePilotApproval() { setPilotBusy(true); setError(""); setSuccess(""); try { const { data: preview } = await getPilotKnowledgeApprovalPreview(courseId); setPilotPreview(preview); } catch (e) { setError(getApiErrorMessage(e, "Unable to prepare pilot approval.")); } finally { setPilotBusy(false); } }
  async function approvePilot() { if (!pilotPreview?.eligible_count) return; const code = window.prompt(`Enter the exact course code (${pilotPreview.course_code}) to confirm:`); if (code === null) return; const reason = window.prompt("Record the controlled-pilot approval declaration (minimum 20 characters):"); if (reason === null) return; setPilotBusy(true); setError(""); try { const { data: result } = await pilotApproveKnowledgePackages(courseId, { course_code: code.trim(), reason: reason.trim(), expected_package_ids: pilotPreview.expected_package_ids }); setPilotPreview(null); await load(); setSuccess(`${result.approved_count} packages approved for controlled pilot use. Independent expert approval remains pending.`); } catch (e) { setError(getApiErrorMessage(e, "Unable to complete pilot approval.")); } finally { setPilotBusy(false); } }
  const courses = data?.courses || []; const items = courses.flatMap((course) => course.items || []); const counts = items.reduce((all,item) => ({...all,[item.status]:(all[item.status]||0)+1}),{});
  return <main className={styles.page}><section className={styles.hero}><small>GOVERNED ACADEMIC CONTENT</small><h1>{admin ? courses[0]?.course_title || "Knowledge Package Reviews" : "My Academic Content Reviews"}</h1><p>Inspect complete evidence, record independent verification and preserve separation between preparation, expert verification and final approval.</p></section>{error && <div className={styles.error}>{error}</div>}{success && <div className={styles.success}>{success}</div>}<section className={styles.metrics}>{["DRAFT","SOURCE_REVIEW","EXPERT_VERIFIED","PILOT_APPROVED","APPROVED"].map((status) => <article className={styles.metric} key={status}><span>{label(status)}</span><strong>{counts[status] || 0}</strong></article>)}</section>{admin && <section className={styles.card}><h2>Controlled pilot approval</h2><p>Administrators may pilot-approve structurally complete benchmark packages without recording false independent expert verification.</p><div className={styles.actions}><button className={styles.secondary} disabled={pilotBusy} onClick={preparePilotApproval}>Preview eligible packages</button>{pilotPreview && <><span>{pilotPreview.eligible_count} of {pilotPreview.package_count} packages eligible</span><button className={styles.primary} disabled={!pilotPreview.eligible_count || pilotBusy} onClick={approvePilot}>Approve all eligible for pilot</button></>}</div>{pilotPreview && <p className={styles.meta}>{pilotPreview.declaration}</p>}</section>}{!data ? <p>Loading review assignments…</p> : !items.length ? <p>No knowledge-package reviews are assigned.</p> : courses.map((course) => <section key={course.course_id}><h2>{!admin && course.course_title}</h2>{course.items.map((item) => <PackageCard key={item.package_id} item={item} admin={admin} faculty={faculty} onRefresh={load} />)}</section>)}</main>;
}
