import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { ArrowDownTrayIcon, ArrowLeftIcon, UserGroupIcon } from "@heroicons/react/24/outline";
import { bulkEnrollCourseStudents, exportCourseEnrollments, getApiErrorMessage, getCourse, getEnrollmentProgrammes, listCourseEnrollments, previewCourseEnrollmentCohort, updateCourseEnrollment } from "../../src/api";
import { downloadBlob } from "../../src/adminMaster";
import AdminShell from "./AdminShell";
import BrandedState from "./BrandedState";
import useAdminAccess from "./useAdminAccess";
import styles from "./CourseEnrollmentWorkspace.module.css";

export default function CourseEnrollmentWorkspace() {
  const router = useRouter(); const access = useAdminAccess(); const id = router.query.id;
  const [course, setCourse] = useState(null); const [filters, setFilters] = useState({ academic_program: "", present_year: "" });
  const [preview, setPreview] = useState(null); const [selected, setSelected] = useState([]); const [enrollments, setEnrollments] = useState([]);
  const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const [programmes, setProgrammes] = useState([]);
  const [programmesReady, setProgrammesReady] = useState(false);
  async function refresh() { const [{ data: courseData }, { data: enrollmentData }, { data: programmeData }] = await Promise.all([getCourse(id), listCourseEnrollments(id), getEnrollmentProgrammes(id)]); setCourse(courseData); setEnrollments(enrollmentData.items || []); setProgrammes(programmeData.academic_programmes || []); setProgrammesReady(true); }
  function changeFilter(name, value) { setFilters((previous) => ({ ...previous, [name]: value })); setPreview(null); setSelected([]); setNotice(""); }
  useEffect(() => { if (access.status === "ready" && router.isReady && id) refresh().catch((e) => setError(getApiErrorMessage(e, "Unable to load course enrollments."))); }, [access.status, router.isReady, id]);
  const payload = () => ({ academic_program: filters.academic_program.trim() || null, present_year: filters.present_year ? Number(filters.present_year) : null, student_ids: [] });
  async function runPreview(event) { event.preventDefault(); setBusy(true); setError(""); setNotice(""); try { const { data } = await previewCourseEnrollmentCohort(id, payload()); setPreview(data); setSelected((data.items || []).filter((row) => row.eligible).map((row) => row.student_id)); } catch (e) { setError(getApiErrorMessage(e, "Unable to preview the enrollment cohort.")); } finally { setBusy(false); } }
  const published = course?.publication_status === "PUBLISHED" && course?.is_active;
  const assignable = published || ["DRAFT", "READY_FOR_REVIEW"].includes(course?.publication_status);
  const statusLabel = (status) => status === "PENDING_ACTIVATION" ? "Pending activation" : status;
  async function confirmEnrollment() { if (!selected.length || !window.confirm(`${published ? "Enroll" : "Assign"} ${selected.length} selected students in ${course.title}? ${published ? "" : "Assignments remain pending until publication and activation."}`)) return; setBusy(true); try { const { data } = await bulkEnrollCourseStudents(id, { ...payload(), student_ids: selected }); setNotice(`${data.created} students ${data.status === "PENDING_ACTIVATION" ? "assigned — pending activation" : "enrolled"}; ${data.skipped} skipped.`); setPreview(null); setSelected([]); await refresh(); } catch (e) { setError(getApiErrorMessage(e, "Unable to complete bulk enrollment.")); } finally { setBusy(false); } }
  async function changeStatus(row, status) { if (!window.confirm(`Change this enrollment to ${status.toLowerCase()}?`)) return; setBusy(true); try { await updateCourseEnrollment(id, row.id, { status }); await refresh(); } catch (e) { setError(getApiErrorMessage(e)); } finally { setBusy(false); } }
  async function downloadExport() { try { const response = await exportCourseEnrollments(id); downloadBlob(response.data, `SYS_${course.programme_code || course.id}_enrollments.csv`); } catch (e) { setError(getApiErrorMessage(e, "Unable to export enrollments.")); } }
  if (access.status === "checking") return <BrandedState title="Verifying administrator access" message="Preparing secure enrollment management." />;
  if (access.status !== "ready") return access.status === "error" ? <BrandedState type="error" title="Enrollment workspace unavailable" message={access.error} /> : null;
  return <><Head><title>Course Enrollments | SYS</title></Head><AdminShell user={access.user} breadcrumb="Academic Management" pageTitle="Course Enrollments" scopeLabel="Platform-wide"><main className={styles.workspace}><Link className={styles.back} href={`/admin/courses/${id}`}><ArrowLeftIcon />Back to course profile</Link><header><div><span>ACADEMIC MANAGEMENT · STUDENT ENROLLMENT</span><h1>{course?.title || "Course Enrollment"}</h1><p>Build an eligible cohort using academic programme and present year, preview every student, and confirm enrollment safely.</p></div><button type="button" onClick={downloadExport} disabled={!course}><ArrowDownTrayIcon />Export enrollments</button></header>{error && <div className={styles.error}>{error}</div>}{notice && <div className={styles.notice}>{notice}</div>}
  <div className={styles.notice}>Course status: {course?.publication_status || "Loading"}. {published ? "New enrollments are active." : assignable ? "Students may be assigned now. Pending assignments do not grant learning access." : "New assignments are blocked for this unavailable course."}</div>
  <section className={styles.card}><h2>1. Select eligible student cohort</h2><form className={styles.filters} onSubmit={runPreview}><label>Academic programme<select value={filters.academic_program} disabled={busy || !programmesReady} onChange={(e) => changeFilter("academic_program", e.target.value)}><option value="">{programmesReady ? "All academic programmes" : "Loading academic programmes…"}</option>{programmes.map((programme) => <option key={programme} value={programme}>{programme}</option>)}</select></label><label>Present year<input type="number" min="1" max="20" disabled={busy} value={filters.present_year} onChange={(e) => changeFilter("present_year", e.target.value)} placeholder="3" /></label><button disabled={busy || !programmesReady || (!filters.academic_program && !filters.present_year)} type="submit">Preview eligible students</button></form><p className={styles.help}>Programmes are loaded from Student Master. Select a programme or present year; both together use AND logic. Preview never creates enrollments.</p>{programmesReady && !programmes.length && <p className={styles.help}>No academic programmes are recorded yet. Update Student Master or select a present year.</p>}</section>
  {preview && <section className={styles.card}><div className={styles.titleRow}><div><h2>2. Review and confirm</h2><p>{preview.summary.matched} matched · {preview.summary.ready} ready · {preview.summary.already_enrolled} already enrolled</p></div><button disabled={busy || !selected.length || !assignable} onClick={confirmEnrollment}>{published ? "Enroll" : "Assign"} {selected.length} selected students</button></div><div className={styles.tableWrap}><table><thead><tr><th>Select</th><th>Roll number</th><th>Student</th><th>Programme & year</th><th>College</th><th>Current state</th></tr></thead><tbody>{preview.items.map((row) => <tr key={row.student_id}><td><input type="checkbox" disabled={!row.eligible} checked={selected.includes(row.student_id)} onChange={() => setSelected((items) => items.includes(row.student_id) ? items.filter((x) => x !== row.student_id) : [...items, row.student_id])} /></td><td>{row.roll_number}</td><td><strong>{row.name}</strong></td><td>{row.academic_program || "Not recorded"}<small>Year {row.present_year || "—"}</small></td><td>{row.college || "Not recorded"}</td><td>{statusLabel(row.enrollment_status) || "Ready"}</td></tr>)}</tbody></table></div></section>}
  <section className={styles.card}><div className={styles.titleRow}><div><h2>Current course enrollments</h2><p>{enrollments.length} verified enrollment records</p></div><UserGroupIcon /></div><div className={styles.tableWrap}><table><thead><tr><th>Roll number</th><th>Student</th><th>Programme & year</th><th>Status</th><th>Source</th><th>Manage</th></tr></thead><tbody>{enrollments.length ? enrollments.map((row) => <tr key={row.id}><td>{row.roll_number}</td><td><strong>{row.student_name}</strong></td><td>{row.academic_program || "Not recorded"}<small>Year {row.present_year || "—"}</small></td><td>{statusLabel(row.status)}</td><td>{row.source}</td><td><select value={row.status} disabled={busy} onChange={(e) => changeStatus(row, e.target.value)}>{["PENDING_ACTIVATION", "ACTIVE", "COMPLETED", "WITHDRAWN", "SUSPENDED"].map((value) => <option key={value} value={value} disabled={(value === "ACTIVE" && !published) || (value === "PENDING_ACTIVATION" && published)}>{statusLabel(value)}</option>)}</select></td></tr>) : <tr><td colSpan="6" className={styles.empty}>No students enrolled yet.</td></tr>}</tbody></table></div></section></main></AdminShell></>;
}
